# Generated by Django 3.2.6 on 2021-08-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binance_api_key', models.CharField(max_length=100, null=True)),
                ('binance_secret_key', models.CharField(max_length=100, null=True)),
                ('external_portfolio', models.JSONField(default=dict)),
                ('preferences', models.JSONField(default=dict)),
                ('name', models.CharField(max_length=100)),
                ('date_checked', models.DateTimeField(null=True)),
            ],
        ),
    ]
