[tool.poetry]
name = "crypto-index-fund-bot"
version = "0.1.0"
description = ""
authors = ["Michael Bianco <mike@mikebian.co>"]

[tool.poetry.dependencies]
python = "^3.7"
python-binance = "^1.0.12"
tabulate = "^0.8.9"
coinbasepro = "^0.3.0"
structlog = "^21.1.0"
colorama = "^0.4.4"
python-dotenv = "^0.18.0"
rich = "^10.6.0"
click = "^8.0.1"
vcrpy = {path = "../../python/vcrpy", develop = true }

[tool.poetry.dev-dependencies]
ipython = "^7.25.0"
ipdb = "^0.13.8"
mypy = "^0.910"
pytest = "^6.2.4"
pytest-recording = "^0.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[pytest]
log_cli = true