version: '3.8'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports: ["5432:5432"]
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:6.2
    restart: unless-stopped
    ports: ["6379:6379"]

volumes:
  postgres-data: null
