name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.6
    - uses: knowsuchagency/poetry-install@v1
    - uses: jpetrucciani/black-check@latest
    - name: Run Tests
      run: |
        python manage.py test
