name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.6
    - name: poetry install
      run: |
        pip install -U pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install
    - name: code formatting
      run: |
        set -eax
        black --version
        black --check .

    - name: Setup node.js (for pyright)
      uses: actions/setup-node@v1
      with:
        node-version: "12"
    - name: Run type checking
      run: |
        npm install -g pyright
        pyright .

    - name: Run Tests
      env:
        DJANGO_FIELD_ENCRYPTION_KEY: v6AYhriFBEktgOrXXdKK0X4IU6noDCfSbqPxJ1fIoW0=
        DJANGO_SECRET_KEY: django-insecure-@o-)qrym-cn6_*mx8dnmy#m4*$j%8wyy+l=)va&pe)9e7@o4i)
      run: |
        python manage.py test
