name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.6
    - name: poetry install
      run: |
        pip install -U pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install
    - name: code formatting
      run: |
        set -eax
        black --version
        black --check .
    - name: Type checking
      run: mypy . --exclude=test --show-error-codes --disable-error-code=import
    - name: Run Tests
      run: |
        python manage.py test
